# Generated by Django 3.2.23 on 2024-01-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicIssueQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('avg_rating', models.FloatField(default=3.0)),
                ('ratings', models.IntegerField(default=1)),
                ('var_rating', models.FloatField(default=1.0)),
                ('embedding', models.JSONField(default=None)),
            ],
        ),
    ]
