# Generated by Django 3.2.23 on 2024-01-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('question', models.TextField()),
                ('rating', models.FloatField(default=3.0)),
            ],
        ),
    ]
